# src/core/vl_models/prompt_variants.py
"""Prompt variants under evaluation, kept apart from the frozen baseline.

The baseline is ``final_puzzle_parser.build_puzzle_prompt()`` and must not change:
every number in ``ai-collab/reports/2026-08-15_vl-p0-p1-baseline.html`` was measured
against it, so editing it in place would silently invalidate the comparison.

``sized`` targets the one failure mode that baseline measurement pinned down: all
three baseline examples are 6x6, and both models mis-read the two 7x7 screenshots as
6x6. It adds an explicit "count the grid first" step plus a 7x7 example.
"""

from src.core.vl_models.final_puzzle_parser import (
    PUZZLE_01_JSON_STR,
    PUZZLE_02_JSON_STR,
    PUZZLE_03_JSON_STR,
)

PROMPT_BASELINE = "baseline"
PROMPT_SIZED = "sized"
PROMPT_CHOICES = (PROMPT_BASELINE, PROMPT_SIZED)

# Synthetic, generated by src.core.puzzle_generation.generate_puzzle(m=7, n=7,
# has_walls=True, num_waypoints=10) under random.seed(20260815), and verified
# solvable by CP-SAT (path length 49 = 7x7).
#
# Deliberately NOT taken from illustrations/puzzle_04 or _06: those are the
# evaluation set, and putting their answers in the prompt would be leakage.
PUZZLE_7X7_SYNTHETIC_JSON_STR = """{
  "layout": [
    ["  ", "  ", "  ", "  ", "  ", "  ", "  "],
    ["  ", "  ", "06", "  ", "  ", "  ", "  "],
    ["  ", "  ", "05", "  ", "  ", "  ", "09"],
    ["  ", "  ", "  ", "  ", "04", "  ", "  "],
    ["  ", "  ", "  ", "03", "  ", "  ", "01"],
    ["  ", "  ", "07", "  ", "  ", "10", "02"],
    ["  ", "  ", "08", "  ", "  ", "  ", "  "]
  ],
  "walls": [
    {"cell1": [2, 5], "cell2": [3, 5]},
    {"cell1": [3, 0], "cell2": [3, 1]},
    {"cell1": [3, 2], "cell2": [3, 3]},
    {"cell1": [3, 4], "cell2": [4, 4]}
  ]
}"""


def build_sized_puzzle_prompt() -> str:
    """Baseline prompt plus an explicit grid-sizing step and a 7x7 example."""
    return f"""
You are an expert Zip puzzle analyzer. Your task is to analyze the provided image and respond with ONLY a single JSON object in a markdown code block.

Before writing the JSON, work out the grid dimensions from the image: count the rows and count the columns. Grids vary in size and are often NOT 6x6 -- 5x5, 7x7 and 8x8 all occur. The "layout" array must have exactly one entry per row, and every row must have exactly one entry per column.

The JSON object must have two keys: "layout" and "walls".
- "layout": A 2D array of strings representing the grid.
- "walls": A list of objects, where each object represents a wall between two cells. A wall is a thick black bar drawn ON a grid line between two neighbouring cells; report every one you can see, and do not invent walls that are not there.

Here are some examples of the required output format. Note that they are not all the same size.

--- EXAMPLE 1 (6x6) ---
```json
{PUZZLE_01_JSON_STR.strip()}
```

--- EXAMPLE 2 (6x6) ---
```json
{PUZZLE_02_JSON_STR.strip()}
```

--- EXAMPLE 3 (6x6) ---
```json
{PUZZLE_03_JSON_STR.strip()}
```

--- EXAMPLE 4 (7x7) ---
```json
{PUZZLE_7X7_SYNTHETIC_JSON_STR.strip()}
```

--- TASK ---
Now, analyze the new image provided and generate the corresponding JSON object in the exact same format. Do not include any other text, explanations, or apologies in your response.
"""
