# .devcontainer/Dockerfile.dev
# This Dockerfile is for the DEVELOPMENT environment.
# It sets up the Python environment but does not build the frontend.

FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel

RUN pip install --no-cache-dir uv

WORKDIR /app

COPY pyproject.toml uv.lock pytest.ini ./

RUN uv sync

COPY src ./src

ENV APP_PORT=7440

EXPOSE 7440
